title: ItsZariep
email: itszariep@disroot.org
description: >- # this means to ignore newlines until "baseurl:"
  Blog de ItsZariep
baseurl: "itszariep.github.io"
url: "/"
github_username: itszariep

# Build settings
remote_theme: itszariep/tessera

social_links:
  - name: GitHub
    url: https://github.com/itszariep
    icon: github
  - name: Telegram
    url: https://t.me/IsZariep
    icon: github
  - name: Youtube
    url: https://youtube.com/@itszariep
    icon: youtube

plugins:
  - jekyll-paginate
  - jekyll-archives

paginate: 9
paginate_path: "/page:num/"

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/categories/:name/'

date_format: "%d/%m/%Y"